test_machines = [
{ "_id": "3120", "key": "3120",  "machine_name": "Glamor Girls", "abbreviation":"GLAM"},
{ "_id": "4604", "key": "4604",  "machine_name": "Gran Casino","abbreviation": "GRAN"},
{ "_id": "990", "key": "990",  "machine_name": "Gay Cruise","abbreviation":  "GAY" },
{ "_id": "3270", "key": "3270",  "machine_name": "Special Force Girls","abbreviation":   "SFG" },
{ "_id": "4603", "key": "4603",  "machine_name": "El Reloj","abbreviation":   "RELO" },
{ "_id": "3977", "key": "3977",  "machine_name": "Selen Cup","abbreviation":   "SELE" },
{ "_id": "3678", "key": "3678",  "machine_name": "Carioca","abbreviation":  "CAR" },
{ "_id": "828", "key": "828",  "machine_name": "Fast Draw","abbreviation":  "FAST" },
{ "_id": "1372", "key": "1372",  "machine_name": "King of Diamonds","abbreviation":  "KING" },
{ "_id": "3450", "key": "3450",  "machine_name": "Magic Picture Pin","abbreviation":  "MAGI" },
{ "_id": "1612", "key": "1612",  "machine_name": "Miss-O","abbreviation":  "MISO" },
{ "_id": "222", "key": "222",  "machine_name": "Pamco Bells","abbreviation":  "BELL" },
{ "_id": "4225", "key": "4225",  "machine_name": "Form-A-Word","abbreviation":  "WORD" },
{ "_id": "2542", "key": "2542",  "machine_name": "Three Point","abbreviation":  "3P" },
{ "_id": "2189", "key": "2189",  "machine_name": "Skipper","abbreviation":  "SKI" },
{ "_id": "3469", "key": "3469",  "machine_name": "Sports Parade","abbreviation":  "SPO" },
{ "_id": "1287", "key": "1287",  "machine_name": "Jay-Ball","abbreviation":  "JAY" },
{ "_id": "1639", "key": "1639",  "machine_name": "Mr. & Mrs. Pac-Man Pinball","abbreviation":  "PAC" },
{ "_id": "4029", "key": "4029",  "machine_name": "Night Hawk","abbreviation":  "HAWK" },
{ "_id": "1021", "key": "1021",  "machine_name": "Goin Nuts","abbreviation":  "NUT" },
{ "_id": "1040", "key": "1040",  "machine_name": "Gold Star","abbreviation":  "GSTR" },
{ "_id": "4440", "key": "4440",  "machine_name": "La Retata","abbreviation":  "RETA" },
{ "_id": "3817", "key": "3817",  "machine_name": "Handicapper","abbreviation":  "HAND" },
{ "_id": "5530", "key": "5530",  "machine_name": "Cherokee Rose","abbreviation":  "CR" },
{ "_id": "6020", "key": "6020",  "machine_name": "Big Inning (Chicago Model)","abbreviation":  "BI" },
{ "_id": "3969", "key": "3969",  "machine_name": "Bloody China","abbreviation":  "BC" },
{ "_id": "1932", "key": "1932",  "machine_name": "Red Ball","abbreviation":  "RB" },
{ "_id": "4298", "key": "4298",  "machine_name": "Position","abbreviation":  "POS" },
{ "_id": "5895", "key": "5895",  "machine_name": "Viking King","abbreviation":  "VK" },
{ "_id": "5464", "key": "5464",  "machine_name": "The Hellacopters","abbreviation":  "HELA" },
{ "_id": "3156", "key": "3156",  "machine_name": "Home Stretch","abbreviation":  "HS" },
{ "_id": "4576", "key": "4576",  "machine_name": "Vortex","abbreviation":  "VOR" },
{ "_id": "5200", "key": "5200",  "machine_name": "Star FLIPP evasion","abbreviation":  "SFE" },
{ "_id": "398", "key": "398",  "machine_name": "Builder Upper","abbreviation":  "BU" },
{ "_id": "1421", "key": "1421",  "machine_name": "Lazer Lord","abbreviation":  "LL" },
{ "_id": "5653", "key": "5653",  "machine_name": "James Cameron s Avatar (Limited Edition)","abbreviation":  "AVA" },
{ "_id": "3550", "key": "3550",  "machine_name": "Whiz Ball Jack Pot","abbreviation":  "WIZ" },
{ "_id": "2846", "key": "2846",  "machine_name": "Fair","abbreviation":  "FAIR" },
{ "_id": "669", "key": "669",  "machine_name": "Derby King","abbreviation":  "DK" },
{ "_id": "783", "key": "783",  "machine_name": "Embryon","abbreviation":  "EMB" },
{ "_id": "1159", "key": "1159",  "machine_name": "Hi-Ride","abbreviation":  "HR" },
{ "_id": "1600", "key": "1600",  "machine_name": "Mills Pay Table","abbreviation":  "MPT" },
{ "_id": "4542", "key": "4542",  "machine_name": "1871 Redgrave Parlor Bagatelle","abbreviation":  "1871" },
{ "_id": "6112", "key": "6112",  "machine_name": "Miss Bonus 2","abbreviation":  "MB2" },
{ "_id": "4319", "key": "4319",  "machine_name": "Majik Keys","abbreviation":  "MK" },
{ "_id": "4396", "key": "4396",  "machine_name": "Angels","abbreviation":  "ANG" },
{ "_id": "5572", "key": "5572",  "machine_name": "Dai Uchuu Ryokou","abbreviation":  "" },
{ "_id": "5245", "key": "5245",  "machine_name": "Whir-Pool Jr.","abbreviation":  "" },
{ "_id": "4382", "key": "4382",  "machine_name": "Whiz Bang","abbreviation":  "" },
{ "_id": "3287", "key": "3287",  "machine_name": "Orbit 1","abbreviation":  "" },
{ "_id": "2425", "key": "2425",  "machine_name": "Sunshine Derby","abbreviation":  "" },
{ "_id": "1935", "key": "1935",  "machine_name": "The Red Max","abbreviation":  "" },
{ "_id": "1560", "key": "1560",  "machine_name": "Mat-Cha-Skor","abbreviation":  "" },
{ "_id": "1645", "key": "1645",  "machine_name": "Mustang","abbreviation":  "" },
{ "_id": "2477", "key": "2477",  "machine_name": "Sweet 21","abbreviation":  "" },
{ "_id": "6272", "key": "6272",  "machine_name": "PROFI Match","abbreviation":  "" },
{ "_id": "6229", "key": "6229",  "machine_name": "Nairobi","abbreviation":  "" },
{ "_id": "2812", "key": "2812",  "machine_name": "World Fair","abbreviation":  "" },
{ "_id": "5667", "key": "5667",  "machine_name": "Khalifa","abbreviation":  "" },
{ "_id": "1249", "key": "1249",  "machine_name": "Hot Springs","abbreviation":  "" },
{ "_id": "213", "key": "213",  "machine_name": "Beat Time","abbreviation":  "" },
{ "_id": "4905", "key": "4905",  "machine_name": "Mini-Viper","abbreviation":  "" },
{ "_id": "4352", "key": "4352",  "machine_name": "Pentogram","abbreviation":  "" },
{ "_id": "888", "key": "888",  "machine_name": "The Flintstones","abbreviation":  "" },
{ "_id": "2508", "key": "2508",  "machine_name": "Teed Off","abbreviation":  "" },
{ "_id": "4051", "key": "4051",  "machine_name": "Miss Americana Triple Bonus","abbreviation":  "" },
{ "_id": "1357", "key": "1357",  "machine_name": "Kew Pin Golf Table","abbreviation":  "" },
{ "_id": "675", "key": "675",  "machine_name": "Diamond Ball","abbreviation":  "" },
{ "_id": "4487", "key": "4487",  "machine_name": "Black Flag","abbreviation":  "" },
{ "_id": "2100", "key": "2100",  "machine_name": "Set Up","abbreviation":  "" },
{ "_id": "1779", "key": "1779",  "machine_name": "Pheasant","abbreviation":  "" },
{ "_id": "1569", "key": "1569",  "machine_name": "Melody Roll","abbreviation":  "" },
{ "_id": "5126", "key": "5126",  "machine_name": "Reviera","abbreviation":  "" },
{ "_id": "4535", "key": "4535",  "machine_name": "Continental Lucky 7","abbreviation":  "" },
{ "_id": "2449", "key": "2449",  "machine_name": "Super Straight","abbreviation":  "" },
{ "_id": "2213", "key": "2213",  "machine_name": "Sluggin Champ","abbreviation":  "" },
{ "_id": "74", "key": "74",  "machine_name": "Angle Lite","abbreviation":  "" },
{ "_id": "2033", "key": "2033",  "machine_name": "Royal Flash","abbreviation":  "" },
{ "_id": "2338", "key": "2338",  "machine_name": "Stage Door Canteen","abbreviation":  "" },
{ "_id": "873", "key": "873",  "machine_name": "Flash Baseball","abbreviation":  "" },
{ "_id": "2453", "key": "2453",  "machine_name": "Superliner","abbreviation":  "" },
{ "_id": "5479", "key": "5479",  "machine_name": "Spry-Ball","abbreviation":  "" },
{ "_id": "1294", "key": "1294",  "machine_name": "Jig-alo Electro-Ball","abbreviation":  "" },
{ "_id": "5444", "key": "5444",  "machine_name": "Circus Romance","abbreviation":  "" },
{ "_id": "5910", "key": "5910",  "machine_name": "Bingo-Cards","abbreviation":  "" },
{ "_id": "1694", "key": "1694",  "machine_name": "Official (Counter)","abbreviation":  "" },
{ "_id": "1570", "key": "1570",  "machine_name": "Memory Lane","abbreviation":  "" },
{ "_id": "4846", "key": "4846",  "machine_name": "Corinthian 10","abbreviation":  "" },
{ "_id": "4142", "key": "4142",  "machine_name": "Royal One Ball","abbreviation":  "" },
{ "_id": "2169", "key": "2169",  "machine_name": "Six-Sixty-Six","abbreviation":  "" },
{ "_id": "1809", "key": "1809",  "machine_name": "Pla-Girl","abbreviation":  "" },
{ "_id": "875", "key": "875",  "machine_name": "Flash Lite","abbreviation":  "" },
{ "_id": "4617", "key": "4617",  "machine_name": "Mach 2.0 Two","abbreviation":  "" },
{ "_id": "1833", "key": "1833",  "machine_name": "Plus and Minus","abbreviation":  "" },
{ "_id": "4562", "key": "4562",  "machine_name": "Last Supper","abbreviation":  "" },
{ "_id": "5161", "key": "5161",  "machine_name": "Kelly Pool (Junior)","abbreviation":  "" },
{ "_id": "1158", "key": "1158",  "machine_name": "Hi Dolly","abbreviation":  "" },
{ "_id": "4502", "key": "4502",  "machine_name": "High Roller Casino","abbreviation":  "" },
{ "_id": "3358", "key": "3358",  "machine_name": "Peppy","abbreviation":  "" },
{ "_id": "4746", "key": "4746",  "machine_name": "Five Star Final","abbreviation": ""}
]
