import auth
import pss_user
import roles
import event
import player
import ifpa
import tournament
import tournament_machine
import token
import stripe_routes
import meta_tournament
import queue
import multi_tournament
import media_upload
import machine
import event_description
import tournament_description
import itsdangerous_route
import testing_routes
